import Head from "next/head";
import About from "../components/home/About";
import ContentUs from "../components/home/ContentUs";
import Display from "../components/home/Display";
import Service from "../components/home/Service";
import axios from "axios";

export default function Home() {
  const object = {
    photos: ["klhj"],
  };
  const featured = {};
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex flex-col  w-full pb-[30px]'>
        <About photo={object?.photos} bio={object?.bio} />
        <Service aim={object?.aim} />
        <Display catalog={featured} />
        <ContentUs />
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const email = process.env.ADMIN_EMAIL;
  const host = "https://fervencciD.onrender.com/api/v1";
  const url = `${host}/users?searchBy=email,${email}&fields=aim,bio,photos`;
  try {
    const data = await axios.get(url);
    const catalog = await axios.get(`${host}/catalogs?limit=20`);
    console.log(data, "wait");

    return {
      props: {
        data: JSON.stringify(data),
        catalog: JSON.stringify(catalog),
      },
    };
  } catch (err) {
    return {
      notFound: true,
    };
  }
}
