import Head from "next/head";
import About from "../components/home/About";
import ContentUs from "../components/home/ContentUs";
import Display from "../components/home/Display";
import Service from "../components/home/Service";
import axios from "axios";
import { useEffect, useState } from "react";

export default function Home({ data }) {
  const user = data.data[0];
  const catalog = data.catalog;
  console.log(data);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex flex-col  w-full pb-[30px]'>
        <About photo={user?.photos || {}} bio={user?.bio || {}} />
        <Service aim={user?.aim || {}} />
        <Display catalog={catalog} />
        <ContentUs />
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const email = process.env.ADMIN_EMAIL;
  const host = "https://fervencciD.onrender.com/api/v1";
  const url = `${host}/users?email=${email}&fields=aim,bio,photos`;
  return axios
    .get(url)
    .then(async (user) => {
      // console.log(user.data, "user");
      const res = user?.data || {};
      const catalog = await axios.get(`${host}/catalogs?limit=20`);
      res.catalog = catalog.data.data;
      return {
        props: {
          data: res,
        },
      };
    })
    .catch((err) => {
      return {
        notFound: true,
      };
    });
  //   const data = await fetch(url);
  //   const catalog = await fetch(`${host}/catalogs?limit=20`);
  //   console.log(data, catalog, "wait", email);
  //   console.log("first");
  //   if (data.data.length !== 0) {
  //     console.log("sec");
  //     return {
  //       props: {
  //         data: JSON.stringify(data.data),
  //         catalog: JSON.stringify(catalog),
  //       },
  //     };
  //   }
  // } catch (err) {
  //   console.log(err, "err");
  //   return {
  //     props: {
  //       error: JSON.stringify(err),
  //     },
  //   };
  // }
}
